import = ["/home/developer1/dotfiles/.config/alacritty/themes/tokyo-night.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 8.0

[font.bold]
family = "FiraCode Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono SemBd"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono Light"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[window]
decorations = "none"
opacity = 1.0

[window.padding]
x = 10
y = 5
